apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-v2
  namespace: demok8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10 # 5% of the CPU
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 20 # 5% of the memory
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # Scale down within 0.5 minute
      policies:
      - type: Pods
        value: 3 # Continue checking to see if there are more than 3 pods.
        periodSeconds: 15 # Check every 15 Seconds
    scaleUp:
      stabilizationWindowSeconds: 30 # Scale up within 0.5 minute
      policies:
      - type: Percent
        value: 10 # Continue checking to see if there are 10% usage of the pods.
        periodSeconds: 15 # Check every 15 Seconds